language: cpp

compiler:
- clang
- gcc

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6' ]
    packages: [ 'g++-4.9', 'gcc-4.9', 'clang-3.6' ]

before_script:
- if [[ ${CXX} == "g++" ]]; then export CXX="g++-4.9" CC="gcc-4.9" ; fi
- if [[ ${CXX} == "clang++" ]]; then export CXX="clang++-3.6" CC="clang-3.6" ; fi
- make

script:
- make
